source "https://rubygems.org"

gem "fluentd", "1.3.2"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.1.0"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 2.1.4"
gem "ffi"
gem "fluent-plugin-webhdfs", "1.2.3"
